spring:
    datasource:
        url: jdbc:mysql://localhost:3306/multiservicesTest
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            format_sql: true
    batch:
        job:
            enable: false
    cache:
        jcache:
            config: classpath:ehcache.xml