server:
    port: 8081
spring:
    application:
        name: Fraud
    datasource:
        url: jdbc:mysql://localhost:3306/multiservices
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            format_sql: true
    batch:
        job:
            enable: false
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8082/eureka