server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/taskfourth
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            format_sql: true
    batch:
        job:
            enable: false